# Generated by Django 2.2.3 on 2019-07-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeScanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='plu',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendorId',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
